version: '3.8'
services:
  ae-wallet-be:
    image: ae-wallet-be
    container_name: ae-wallet-be
    build: .
    ports:
      - "8080:8080"
      - "8443:8443"
      - "5005:5005"
    secrets:
      - encryption_key
      - ssl_key_store_password
      - ssl_key_store_path
      - ssl_key_store_alias
      - ssl_key_store_type

secrets:
  encryption_key:
    file: ./secrets/aes.secret
  ssl_key_store_password:
    file: ./secrets/ssl_key_store_password.secret
  ssl_key_store_path:
    file: ./secrets/ssl_key_store_path.secret
  ssl_key_store_alias:
    file: ./secrets/ssl_key_store_alias.secret
  ssl_key_store_type:
    file: ./secrets/ssl_key_store_type.secret