spring:
  application:
    name: Wallets

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        cache:
          use_second_level_cache: false

server:
  address: 0.0.0.0
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: ${KEYSTORE_PASSWORD}
    key-store-type: PKCS12
  compression:
    enabled: true
  http2:
    enabled: true

logging:
  level:
    root: WARN
    org.springframework.security: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql: ERROR
    it.aredegalli: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

security:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
  crypto:
    aes-secret-key: ${AES_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, beans, metrics, env
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    db:
      enabled: true
    diskspace:
      enabled: true

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

praetor:
  url: ${PRAETOR_URL}
  applicationName: ${PRAETOR_APP_NAME}